#use 3.2 or higher
version: '3.2'
services:
  web:
    build: web
    ports:
#if 8080 used
      - "8181:8080"
    networks:
      - app42net

  db:
    image: mysql:5
    environment:
      MYSQL_DATABASE: app42
      MYSQL_USER: app42W
      MYSQL_PASSWORD: jc31d2
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - type: bind
        source: ./mysql
        target: /var/lib/mysql
    networks:
      - app42net

networks:
  app42net: